[package]
name = "ledger_manager_cli"
version = "0.1.0"
authors = ["Antoine Poinsot <darosior@protonmail.com>"]

edition.workspace = true
license-file.workspace = true
readme.workspace = true

[dependencies]
ledger_manager = { path = "../ledger_manager" }
